name: iflex
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: 3.0.1

dependencies:

  cupertino_icons: ^1.0.2
  get:
  flutter_spinkit:
  http:

  animated_notch_bottom_bar:
  flutter_typeahead:
  flutter_screenutil:
  flutter_contacts:
  url_launcher:
  get_storage:
  google_fonts:
  eva_icons_flutter:
  flutter_svg:
  flutter_image_compress:
  intl:
  lottie:
  flutter_launcher_icons:







  flutter: 
    sdk: flutter



dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/

flutter_icons:

  ios: true
  android: true
  image_path_ios: "images/logo.jpeg"
  image_path_android: "images/logo.jpeg"
#  adaptive_icon_background: "assets/launcher/background.png"
#  adaptive_icon_foreground: "assets/launcher/foreground.png"