name: iflex
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: 2.19.0-146.2.beta

dependencies:

  cupertino_icons: ^1.0.2
  get:
  flutter_spinkit:
  http:

  animated_notch_bottom_bar:
  flutter_screenutil:
  flutter_contacts:
  url_launcher:
  get_storage:
  google_fonts:
  eva_icons_flutter:
  flutter_svg:
  flutter_image_compress:
  intl:
  lottie:







  flutter: 
    sdk: flutter



dev_dependencies:

  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - images/

